/* const cards = {
   "Knight": "common",
   "Archers": "common",
   "Goblins": "",
   "Giant": "",
   "P.E.K.K.A": "",
   "Minions": "",
   "Balloon": "",
   "Witch": "",
   "Barbarians": "",
   "Golem": "",
   "Skeletons": "",
   "Valkyrie": "",
   "Skeleton Army": "",
   "Bomber": "",
   "Musketeer": "",
   "Baby Dragon": "",
   "Prince": "",
   "Wizard": "",
   "Mini P.E.K.K.A": "",
   "Spear Goblins": "",
   "Giant Skeleton": "",
   "Hog Rider": "",
   "Minion Horde": "",
   "Ice Wizard": "",
   "Royal Giant": "",
   "Guards": "",
   "Princess": "",
   "Dark Prince": "",
   "Three Musketeers": "",
   "Lava Hound": "",
   "Ice Spirit": "",
   "Fire Spirits": "",
   "Miner": "",
   "Sparky": "",
   "Bowler": "",
   "Lumberjack": "",
   "Battle Ram": "",
   "Inferno Dragon": "",
   "Ice Golem": "",
   "Mega Minion": "",
   "Dart Goblin": "",
   "Goblin Gang": "",
   "Electro Wizard": "",
   "Elite Barbarians": "",
   "Hunter": "",
   "Executioner": "",
   "Bandit": "",
   "Royal Recruits": "",
   "Night Witch": "",
   "Bats": "",
   "Royal Ghost": "",
   "Ram Rider": "",
   "Zappies": "",
   "Rascals": "",
   "Cannon Cart": "",
   "Mega Knight": "",
   "Skeleton Barrel": "",
   "Flying Machine": "",
   "Wall Breakers": "",
   "Royal Hogs": "",
   "Goblin Giant": "",
   "Fisherman": "",
   "Magic Archer": "",
   "Electro Dragon": "",
   "Firecracker": "",
   "Elixir Golem": "",
   "Battle Healer": "",
   "Skeleton Dragons": "",
   "Cannon": "",
   "Goblin Hut": "",
   "Mortar": "",
   "Inferno Tower": "",
   "Bomb Tower": "",
   "Barbarian Hut": "",
   "Tesla": "",
   "Elixir Collector": "",
   "X-Bow": "",
   "Tombstone": "",
   "Furnace": "",
   "Goblin Cage": "",
   "Fireball": "",
   "Arrows": "",
   "Rage": "",
   "Rocket": "",
   "Goblin Barrel": "",
   "Freeze": "",
   "Mirror": "",
   "Lightning": "",
   "Zap": "",
   "Poison": "",
   "Graveyard": "",
   "The Log": "",
   "Tornado": "",
   "Clone": "",
   "Earthquake": "",
   "Barbarian Barrel": "",
   "Heal Spirit": "",
   "Giant Snowball": "",
   "Royal Delivery": "",
} */


/* 
   Common 
   Rare 
   Epic
   Legendary 
*/